# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1458000523);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1458000643);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1458073224);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1458000403);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1458000283);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1458000763);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1458073234674");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1458075017674");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1458073240497");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1458076840497");
user_pref("browser.search.countryCode", "PL");
user_pref("browser.search.region", "PL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234718");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20160209234718");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456944703072");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1456858387607");
user_pref("datareporting.policy.firstRunTime", "1456858303070");
user_pref("datareporting.sessions.current.activeTicks", 19);
user_pref("datareporting.sessions.current.firstPaint", 68636);
user_pref("datareporting.sessions.current.main", 7260);
user_pref("datareporting.sessions.current.sessionRestored", 95380);
user_pref("datareporting.sessions.current.startTime", "1458073071414");
user_pref("datareporting.sessions.current.totalTime", 559);
user_pref("datareporting.sessions.currentIndex", 9);
user_pref("datareporting.sessions.previous.1", "{\"s\":1457560083732,\"a\":27,\"t\":3582,\"c\":true,\"m\":3741,\"fp\":52435,\"sr\":59408}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1457564579625,\"a\":0,\"t\":26,\"c\":false,\"m\":3417,\"fp\":39962,\"sr\":39782}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1457564936510,\"a\":0,\"t\":28,\"c\":false,\"m\":1891,\"fp\":51392,\"sr\":49830}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1457643112183,\"a\":2,\"t\":72,\"c\":false,\"m\":3526,\"fp\":48586,\"sr\":65281}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1457644000165,\"a\":134,\"t\":9510,\"c\":true,\"m\":1843,\"fp\":18880,\"sr\":24935}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1457878183060,\"a\":91,\"t\":29542,\"c\":true,\"m\":6254,\"fp\":67468,\"sr\":105266}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1457997082658,\"a\":0,\"t\":56,\"c\":false,\"m\":11339,\"fp\":76435,\"sr\":81940}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1458000035006,\"a\":11,\"t\":1567,\"c\":true,\"m\":1159,\"fp\":22231,\"sr\":27596}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1458000525);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455750937000,\"mt\":1455063905000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064670000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064670000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1458073682);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1456858397);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234718");
user_pref("media.gmp-manager.lastCheck", 1458000118);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1457560409);
user_pref("places.history.expiration.transient_current_max_pages", 31104);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1457560409);
user_pref("toolkit.startup.last_success", 1458073078);
user_pref("toolkit.telemetry.cachedClientID", "584f6f50-ff61-43e7-8d3d-a658c9f6f5b5");
user_pref("toolkit.telemetry.previousBuildID", "20160209234718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
